# Generated by Django 5.2.18 on 2026-10-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('content_hash', models.CharField(max_length=64)),
                ('loc', models.IntegerField(default=0)),
                ('is_test', models.BooleanField(default=False)),
                ('indexed_sha', models.CharField(blank=True, max_length=64)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repos.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualified_name', models.CharField(max_length=512)),
                ('kind', models.CharField(max_length=32)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('signature', models.TextField(blank=True)),
                ('exported', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='indexing.indexedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('imports', 'Imports'), ('calls', 'Calls'), ('tests', 'Tests')], max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='repos.repository')),
                ('from_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='indexing.indexedfile')),
                ('to_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='indexing.indexedfile')),
                ('from_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='indexing.symbol')),
                ('to_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='indexing.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('token_count', models.IntegerField()),
                ('search_tokens', models.TextField(default=' ')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='indexing.indexedfile')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='indexing.symbol')),
            ],
        ),
        migrations.AddConstraint(
            model_name='indexedfile',
            constraint=models.UniqueConstraint(fields=('repository', 'path'), name='uniq_file_per_repo'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['file', 'qualified_name'], name='indexing_sy_file_id_9a03a6_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['name'], name='indexing_sy_name_621517_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['repository', 'kind', 'to_symbol'], name='indexing_ed_reposit_410c25_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['repository', 'kind', 'from_symbol'], name='indexing_ed_reposit_368698_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['repository', 'kind', 'to_file'], name='indexing_ed_reposit_120181_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['repository', 'kind', 'from_file'], name='indexing_ed_reposit_bb4373_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['file'], name='indexing_ch_file_id_fa1a73_idx'),
        ),
    ]
