# Generated by Django 5.2.18 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('delivery_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
