# Generated by Django 5.2.18 on 2026-10-07 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_installation_id', models.BigIntegerField(unique=True)),
                ('account_login', models.CharField(max_length=255)),
                ('account_type', models.CharField(default='User', max_length=32)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='repos.installation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'installation'), name='uniq_member_per_installation')],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('indexed_sha', models.CharField(blank=True, max_length=64)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('file_count', models.IntegerField(default=0)),
                ('symbol_count', models.IntegerField(default=0)),
                ('edge_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='repos.installation')),
            ],
            options={
                'indexes': [models.Index(fields=['installation', 'full_name'], name='repos_repos_install_a727c3_idx')],
            },
        ),
    ]
