# Generated by Django 5.2.18 on 2026-10-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(blank=True, max_length=512)),
                ('head_sha', models.CharField(max_length=64)),
                ('base_sha', models.CharField(blank=True, max_length=64)),
                ('trigger_comment_id', models.BigIntegerField()),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('aethos', 'Aethos'), ('baseline', 'Baseline')], default='aethos', max_length=16)),
                ('dry_run', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('triaged', 'Triaged'), ('packed', 'Packed'), ('reviewed', 'Reviewed'), ('posted', 'Posted'), ('skipped', 'Skipped'), ('superseded', 'Superseded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('skip_reason', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('risk', models.CharField(blank=True, max_length=16)),
                ('verdict', models.CharField(blank=True, max_length=32)),
                ('verdict_reasons', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('pack', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('github_review_id', models.BigIntegerField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('tokens_cached', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='repos.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('line', models.IntegerField()),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(max_length=16)),
                ('confidence', models.FloatField()),
                ('category', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('posted_inline', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('tokens_cached', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='reviews.review')),
            ],
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['repository', '-created_at'], name='reviews_rev_reposit_1617e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('repository', 'pr_number', 'head_sha', 'trigger_comment_id', 'mode'), name='uniq_review_per_trigger'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['review'], name='reviews_fin_review__37f2e9_idx'),
        ),
    ]
