/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["apps_accounts_api_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login View */
        get: operations["apps_accounts_api_login_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout View */
        post: operations["apps_accounts_api_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["apps_accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["apps_dashboard_api_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repos */
        get: operations["apps_dashboard_api_repos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/repos/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repo Detail */
        get: operations["apps_dashboard_api_repo_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/repos/{repo_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex
         * @description Queue a fresh index of the default branch.
         */
        post: operations["apps_dashboard_api_reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/repos/{repo_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["apps_dashboard_api_update_settings"];
        trace?: never;
    };
    "/api/dashboard/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews */
        get: operations["apps_dashboard_api_reviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Detail */
        get: operations["apps_dashboard_api_review_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspaces */
        get: operations["apps_dashboard_api_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FindingOut */
        FindingOut: {
            /** Body */
            body: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Line */
            line: number;
            /** Path */
            path: string;
            /** Posted Inline */
            posted_inline: boolean;
            /** Severity */
            severity: string;
            /** Suggestion */
            suggestion: string;
            /** Title */
            title: string;
        };
        /** MeOut */
        MeOut: {
            /** Avatar Url */
            avatar_url: string;
            /** Csrf Token */
            csrf_token: string;
            /** Install Url */
            install_url: string;
            /** Login */
            login: string;
        };
        /** OverviewOut */
        OverviewOut: {
            /** Cost Usd */
            cost_usd: number;
            /** Days */
            days: number;
            /** Reviews Posted */
            reviews_posted: number;
            /** Reviews Skipped */
            reviews_skipped: number;
            /** Reviews Total */
            reviews_total: number;
            savings: components["schemas"]["Savings"];
            /** Series */
            series: components["schemas"]["SeriesPoint"][];
            severities: components["schemas"]["SeverityCounts"];
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            verdicts: components["schemas"]["VerdictCounts"];
        };
        /** RepoOut */
        RepoOut: {
            /** Chunk Count */
            chunk_count: number;
            /** Default Branch */
            default_branch: string;
            /** Edge Count */
            edge_count: number;
            /** Embedded Count */
            embedded_count: number;
            /** File Count */
            file_count: number;
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
            /** Index Status */
            index_status: string;
            /** Indexed Sha */
            indexed_sha: string;
            /** Is Private */
            is_private: boolean;
            /** Last Indexed At */
            last_indexed_at: string | null;
            /** Review Count */
            review_count: number;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /** Symbol Count */
            symbol_count: number;
        };
        /** ReviewDetail */
        ReviewDetail: {
            /** Cost Usd */
            cost_usd: number;
            /** Created At */
            created_at: string;
            /** Error */
            error: string;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Id */
            id: number;
            /** Instructions */
            instructions: string;
            /** Latency Ms */
            latency_ms: number;
            /** Mode */
            mode: string;
            /** Pack */
            pack: {
                [key: string]: unknown;
            } | null;
            /** Pr Number */
            pr_number: number;
            /** Pr Title */
            pr_title: string;
            /** Pr Url */
            pr_url: string;
            /** Repo */
            repo: string;
            /** Repo Id */
            repo_id: number;
            /** Risk */
            risk: string;
            /** Skip Reason */
            skip_reason: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Usage */
            usage: components["schemas"]["UsageOut"][];
            /** Verdict */
            verdict: string;
            /** Verdict Reasons */
            verdict_reasons: {
                [key: string]: unknown;
            }[];
        };
        /** ReviewListItem */
        ReviewListItem: {
            /** Cost Usd */
            cost_usd: number;
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Latency Ms */
            latency_ms: number;
            /** Mode */
            mode: string;
            /** Pr Number */
            pr_number: number;
            /** Pr Title */
            pr_title: string;
            /** Pr Url */
            pr_url: string;
            /** Repo */
            repo: string;
            /** Repo Id */
            repo_id: number;
            /** Risk */
            risk: string;
            /** Skip Reason */
            skip_reason: string;
            /** Status */
            status: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Verdict */
            verdict: string;
        };
        /** Savings */
        Savings: {
            /** Aethos Tokens In */
            aethos_tokens_in: number;
            /** Baseline Tokens In */
            baseline_tokens_in: number;
            /** Pairs */
            pairs: number;
            /** Saved Pct */
            saved_pct: number | null;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Cost Usd */
            cost_usd: number;
            /** Date */
            date: string;
            /** Reviews */
            reviews: number;
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Block On */
            block_on?: components["schemas"]["Severity"][] | null;
            /** Enabled */
            enabled?: boolean | null;
            /** High Risk Paths */
            high_risk_paths?: string[] | null;
            /** Ignore Paths */
            ignore_paths?: string[] | null;
            /** Max Comments */
            max_comments?: number | null;
            /** Min Confidence */
            min_confidence?: number | null;
            /** Mode */
            mode?: string | null;
            /** Pack Tokens */
            pack_tokens?: number | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "nit";
        /** SeverityCounts */
        SeverityCounts: {
            /** Critical */
            critical: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Medium */
            medium: number;
            /** Nit */
            nit: number;
        };
        /** UsageOut */
        UsageOut: {
            /** Cost Usd */
            cost_usd: number;
            /** Duration Ms */
            duration_ms: number;
            /** Model */
            model: string;
            /** Step */
            step: string;
            /** Tokens Cached */
            tokens_cached: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** VerdictCounts */
        VerdictCounts: {
            /** Inconclusive */
            inconclusive: number;
            /** Not Ready */
            not_ready: number;
            /** Ready */
            ready: number;
            /** Ready With Suggestions */
            ready_with_suggestions: number;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Account Type */
            account_type: string;
            /** Login */
            login: string;
            /** Repo Count */
            repo_count: number;
            /** Suspended */
            suspended: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apps_accounts_api_callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_login_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    apps_dashboard_api_overview: {
        parameters: {
            query?: {
                days?: number;
                workspace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    apps_dashboard_api_repos: {
        parameters: {
            query?: {
                workspace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoOut"][];
                };
            };
        };
    };
    apps_dashboard_api_repo_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoOut"];
                };
            };
        };
    };
    apps_dashboard_api_reindex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoOut"];
                };
            };
        };
    };
    apps_dashboard_api_update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoOut"];
                };
            };
        };
    };
    apps_dashboard_api_reviews: {
        parameters: {
            query?: {
                repo_id?: number | null;
                limit?: number;
                offset?: number;
                workspace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListItem"][];
                };
            };
        };
    };
    apps_dashboard_api_review_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetail"];
                };
            };
        };
    };
    apps_dashboard_api_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"][];
                };
            };
        };
    };
}
